/* Generated by Yosys 0.45 (git sha1 9ed031ddd, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* \library  = "work" *)
(* hdlname = "priority_enc" *)
(* src = "priority_pre.sv:1.8-1.20" *)
module priority_enc(enc_o, vec_i);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* hdlname = "bsg addr[0]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  wire [7:0] \bsg.addr[0] ;
  (* hdlname = "bsg addr[1]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  (* unused_bits = "0 2 4 6" *)
  wire [7:0] \bsg.addr[1] ;
  (* hdlname = "bsg addr[2]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  (* unused_bits = "0 1 4 5" *)
  wire [7:0] \bsg.addr[2] ;
  (* hdlname = "bsg addr[3]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  wire [7:0] \bsg.addr[3] ;
  (* hdlname = "bsg addr_o" *)
  (* src = "bsg_encode_one_hot.sv:15.32-15.38" *)
  wire [2:0] \bsg.addr_o ;
  (* hdlname = "bsg i" *)
  (* src = "bsg_encode_one_hot.sv:14.22-14.23" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [7:0] \bsg.i ;
  (* hdlname = "bsg rof[1].rof1[0].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "0 1" *)
  wire [1:0] \bsg.rof[1].rof1[0].vs ;
  (* hdlname = "bsg rof[1].rof1[1].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "0 1" *)
  wire [1:0] \bsg.rof[1].rof1[1].vs ;
  (* hdlname = "bsg rof[1].rof1[2].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "0 1" *)
  wire [1:0] \bsg.rof[1].rof1[2].vs ;
  (* hdlname = "bsg rof[1].rof1[3].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "0" *)
  wire [1:0] \bsg.rof[1].rof1[3].vs ;
  (* hdlname = "bsg rof[2].rof1[0].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "0" *)
  wire [1:0] \bsg.rof[2].rof1[0].vs ;
  (* hdlname = "bsg rof[2].rof1[1].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "0" *)
  wire [1:0] \bsg.rof[2].rof1[1].vs ;
  (* hdlname = "bsg rof[3].rof1[0].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  wire [1:0] \bsg.rof[3].rof1[0].vs ;
  (* hdlname = "bsg v[0]" *)
  (* src = "bsg_encode_one_hot.sv:27.44-27.45" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [7:0] \bsg.v[0] ;
  (* hdlname = "bsg v[1]" *)
  (* src = "bsg_encode_one_hot.sv:27.44-27.45" *)
  (* unused_bits = "0 4" *)
  wire [7:0] \bsg.v[1] ;
  (* hdlname = "bsg v[2]" *)
  (* src = "bsg_encode_one_hot.sv:27.44-27.45" *)
  wire [7:0] \bsg.v[2] ;
  (* src = "priority_pre.sv:4.37-4.42" *)
  output [2:0] enc_o;
  wire [2:0] enc_o;
  (* src = "priority_pre.sv:3.28-3.33" *)
  input [7:0] vec_i;
  wire [7:0] vec_i;
  assign _00_ = ~(vec_i[1] & vec_i[0]);
  assign _01_ = ~(vec_i[3] & vec_i[2]);
  assign enc_o[2] = _01_ | _00_;
  assign _02_ = ~(vec_i[2] & vec_i[0]);
  assign _03_ = ~(vec_i[6] & vec_i[4]);
  assign enc_o[0] = _03_ | _02_;
  assign _04_ = ~(vec_i[5] & vec_i[4]);
  assign enc_o[1] = _04_ | _00_;
  assign \bsg.addr[0]  = 8'hxx;
  assign { \bsg.addr[1] [7], \bsg.addr[1] [5], \bsg.addr[1] [3], \bsg.addr[1] [1] } = 4'hx;
  assign { \bsg.addr[2] [7:6], \bsg.addr[2] [3:2] } = 4'hx;
  assign \bsg.addr[3]  = { 5'hxx, enc_o };
  assign \bsg.addr_o  = enc_o;
  assign { \bsg.i [7:6], \bsg.i [4], \bsg.i [2], \bsg.i [0] } = { 1'hx, \bsg.addr[1] [6], \bsg.addr[1] [4], \bsg.addr[1] [2], \bsg.addr[1] [0] };
  assign \bsg.rof[1].rof1[0].vs  = { \bsg.i [1], \bsg.addr[1] [0] };
  assign \bsg.rof[1].rof1[1].vs  = { \bsg.i [3], \bsg.addr[1] [2] };
  assign \bsg.rof[1].rof1[2].vs  = { \bsg.i [5], \bsg.addr[1] [4] };
  assign \bsg.rof[1].rof1[3].vs  = { 1'hx, \bsg.addr[1] [6] };
  assign \bsg.rof[2].rof1[0].vs  = { 1'hx, \bsg.addr[2] [1] };
  assign \bsg.rof[2].rof1[1].vs  = { 1'hx, \bsg.addr[2] [5] };
  assign \bsg.rof[3].rof1[0].vs  = { 1'hx, enc_o[2] };
  assign \bsg.v[0]  = { 1'hx, \bsg.addr[1] [6], \bsg.i [5], \bsg.addr[1] [4], \bsg.i [3], \bsg.addr[1] [2], \bsg.i [1], \bsg.addr[1] [0] };
  assign \bsg.v[1]  = { 3'hx, \bsg.addr[2] [5], 3'hx, \bsg.addr[2] [1] };
  assign \bsg.v[2]  = { 7'hxx, enc_o[2] };
endmodule
