/* Generated by Yosys 0.45 (git sha1 9ed031ddd, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* \library  = "work" *)
(* hdlname = "dff" *)
(* src = "dff.sv:5.8-5.11" *)
module dff(reset_i, d_i, en_i, q_o, clk_i);
  (* src = "dff.sv:7.16-7.21" *)
  input clk_i;
  wire clk_i;
  (* src = "dff.sv:9.16-9.19" *)
  input d_i;
  wire d_i;
  (* src = "dff.sv:10.16-10.20" *)
  input en_i;
  wire en_i;
  (* src = "dff.sv:11.17-11.20" *)
  output q_o;
  wire q_o;
  (* src = "dff.sv:14.16-14.19" *)
  reg q_r;
  (* src = "dff.sv:8.16-8.23" *)
  input reset_i;
  wire reset_i;
  (* src = "dff.sv:24.7-28.10" *)
  always @(posedge clk_i, posedge reset_i)
    if (reset_i) q_r <= 1'h0;
    else if (en_i) q_r <= d_i;
  assign q_o = q_r;
endmodule
