/* Generated by Yosys 0.39 (git sha1 00338082b, aarch64-apple-darwin21.4-clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* hdlname = "half_add" *)
(* src = "half_add.soln.sv:1.8-1.16" *)
module half_add(b_i, carry_o, sum_o, a_i);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "half_add.soln.sv:2.16-2.19" *)
  input a_i;
  wire a_i;
  (* src = "half_add.soln.sv:3.16-3.19" *)
  input b_i;
  wire b_i;
  (* src = "half_add.soln.sv:4.17-4.24" *)
  output carry_o;
  wire carry_o;
  (* src = "half_add.soln.sv:5.17-5.22" *)
  output sum_o;
  wire sum_o;
  assign sum_o = b_i & a_i;
  assign _00_ = _05_ & _06_;
  assign _01_ = b_i & a_i;
  assign _02_ = _03_ & _04_;
  assign _06_ = ~_02_;
  assign _03_ = ~b_i;
  assign _04_ = ~a_i;
  assign _05_ = ~_01_;
  assign carry_o = _00_;
endmodule
