/* Generated by Yosys 0.45 (git sha1 9ed031ddd, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* \library  = "work" *)
(* hdlname = "one_hot_mux" *)
(* src = "priority_pre.sv:1.8-1.19" *)
module one_hot_mux(out_o, vec_i, sel_i);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[0] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[1] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[2] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[3] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[4] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[5] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[6] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[7] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[8] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[9] ;
  (* hdlname = "one_hot_encode bsg addr[0]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  wire [15:0] \one_hot_encode.bsg.addr[0] ;
  (* hdlname = "one_hot_encode bsg addr[1]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  wire [15:0] \one_hot_encode.bsg.addr[1] ;
  (* hdlname = "one_hot_encode bsg addr[2]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  (* unused_bits = "8 9 12 13" *)
  wire [15:0] \one_hot_encode.bsg.addr[2] ;
  (* hdlname = "one_hot_encode bsg addr[3]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  (* unused_bits = "8 9 10" *)
  wire [15:0] \one_hot_encode.bsg.addr[3] ;
  (* hdlname = "one_hot_encode bsg addr[4]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  (* unused_bits = "0 1 2 3" *)
  wire [15:0] \one_hot_encode.bsg.addr[4] ;
  (* hdlname = "one_hot_encode bsg addr_o" *)
  (* src = "bsg_encode_one_hot.sv:15.32-15.38" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] \one_hot_encode.bsg.addr_o ;
  (* hdlname = "one_hot_encode bsg i" *)
  (* src = "bsg_encode_one_hot.sv:14.22-14.23" *)
  (* unused_bits = "9" *)
  wire [9:0] \one_hot_encode.bsg.i ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[0].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[0].vs ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[1].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[1].vs ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[2].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[2].vs ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[3].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[3].vs ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[4].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[4].vs ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[5].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[5].vs ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[6].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[6].vs ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[7].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "1" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[7].vs ;
  (* hdlname = "one_hot_encode bsg rof[2].rof1[0].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  wire [1:0] \one_hot_encode.bsg.rof[2].rof1[0].vs ;
  (* hdlname = "one_hot_encode bsg rof[2].rof1[1].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "1" *)
  wire [1:0] \one_hot_encode.bsg.rof[2].rof1[1].vs ;
  (* hdlname = "one_hot_encode bsg rof[2].rof1[2].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "0" *)
  wire [1:0] \one_hot_encode.bsg.rof[2].rof1[2].vs ;
  (* hdlname = "one_hot_encode bsg rof[2].rof1[3].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "0" *)
  wire [1:0] \one_hot_encode.bsg.rof[2].rof1[3].vs ;
  (* hdlname = "one_hot_encode bsg rof[3].rof1[0].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "1" *)
  wire [1:0] \one_hot_encode.bsg.rof[3].rof1[0].vs ;
  (* hdlname = "one_hot_encode bsg rof[3].rof1[1].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "0" *)
  wire [1:0] \one_hot_encode.bsg.rof[3].rof1[1].vs ;
  (* hdlname = "one_hot_encode bsg rof[4].rof1[0].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "0" *)
  wire [1:0] \one_hot_encode.bsg.rof[4].rof1[0].vs ;
  (* hdlname = "one_hot_encode bsg v[0]" *)
  (* src = "bsg_encode_one_hot.sv:27.44-27.45" *)
  (* unused_bits = "15" *)
  wire [15:0] \one_hot_encode.bsg.v[0] ;
  (* hdlname = "one_hot_encode bsg v[1]" *)
  (* src = "bsg_encode_one_hot.sv:27.44-27.45" *)
  (* unused_bits = "6 8 12" *)
  wire [15:0] \one_hot_encode.bsg.v[1] ;
  (* hdlname = "one_hot_encode bsg v[2]" *)
  (* src = "bsg_encode_one_hot.sv:27.44-27.45" *)
  (* unused_bits = "4 8" *)
  wire [15:0] \one_hot_encode.bsg.v[2] ;
  (* hdlname = "one_hot_encode bsg v[3]" *)
  (* src = "bsg_encode_one_hot.sv:27.44-27.45" *)
  (* unused_bits = "0" *)
  wire [15:0] \one_hot_encode.bsg.v[3] ;
  (* hdlname = "one_hot_encode enc_o" *)
  (* src = "priority_pre.sv:26.37-26.42" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] \one_hot_encode.enc_o ;
  (* hdlname = "one_hot_encode vec_i" *)
  (* src = "priority_pre.sv:25.28-25.33" *)
  (* unused_bits = "9" *)
  wire [9:0] \one_hot_encode.vec_i ;
  (* src = "priority_pre.sv:5.12-5.17" *)
  output out_o;
  wire out_o;
  (* src = "priority_pre.sv:3.27-3.32" *)
  input [9:0] sel_i;
  wire [9:0] sel_i;
  (* src = "priority_pre.sv:7.35-7.40" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] sel_w;
  (* src = "priority_pre.sv:4.27-4.32" *)
  input [9:0] vec_i;
  wire [9:0] vec_i;
  assign _00_ = sel_i[4] | sel_i[2];
  assign _01_ = sel_i[8] | sel_i[6];
  assign _02_ = ~(_01_ | _00_);
  assign _03_ = _02_ & ~(sel_i[0]);
  assign _04_ = _03_ ? vec_i[0] : vec_i[1];
  assign _05_ = ~(sel_i[3] | sel_i[2]);
  assign _06_ = sel_i[7] | sel_i[6];
  assign _07_ = _05_ & ~(_06_);
  assign _08_ = _03_ ? vec_i[2] : vec_i[3];
  assign _09_ = _07_ ? _04_ : _08_;
  assign _10_ = sel_i[5] | sel_i[4];
  assign _11_ = _05_ & ~(_10_);
  assign _12_ = _03_ ? vec_i[4] : vec_i[5];
  assign _13_ = _03_ ? vec_i[6] : vec_i[7];
  assign _14_ = _07_ ? _12_ : _13_;
  assign _15_ = _11_ ? _09_ : _14_;
  assign _16_ = ~(sel_i[1] | sel_i[0]);
  assign _17_ = _03_ ? vec_i[8] : vec_i[9];
  assign _18_ = ~(_17_ & _07_);
  assign _19_ = _11_ & ~(_18_);
  assign out_o = _16_ ? _15_ : _19_;
  assign \elems[0]  = vec_i[0];
  assign \elems[1]  = vec_i[1];
  assign \elems[2]  = vec_i[2];
  assign \elems[3]  = vec_i[3];
  assign \elems[4]  = vec_i[4];
  assign \elems[5]  = vec_i[5];
  assign \elems[6]  = vec_i[6];
  assign \elems[7]  = vec_i[7];
  assign \elems[8]  = vec_i[8];
  assign \elems[9]  = vec_i[9];
  assign \one_hot_encode.bsg.addr[0]  = 16'hxxxx;
  assign \one_hot_encode.bsg.addr[1]  = { 1'hx, sel_i[8], 1'hx, sel_i[6], 1'hx, sel_i[4], 1'hx, sel_i[2], 1'hx, sel_i[0], 6'bx0x0x0 };
  assign { \one_hot_encode.bsg.addr[2] [15:14], \one_hot_encode.bsg.addr[2] [11:10], \one_hot_encode.bsg.addr[2] [7:0] } = { 7'bxxxxxx0, sel_i[0], 4'bxx00 };
  assign { \one_hot_encode.bsg.addr[3] [15:11], \one_hot_encode.bsg.addr[3] [7:0] } = { 12'bxxxxxxxxxx00, sel_i[0] };
  assign { \one_hot_encode.bsg.addr[4] [15:4], \one_hot_encode.bsg.addr[4] [2:1] } = { 12'hxxx, \one_hot_encode.bsg.addr[3] [10:9] };
  assign \one_hot_encode.bsg.addr_o  = { \one_hot_encode.bsg.addr[4] [3], \one_hot_encode.bsg.addr[3] [10:9], \one_hot_encode.bsg.addr[4] [0] };
  assign \one_hot_encode.bsg.i  = sel_i;
  assign \one_hot_encode.bsg.rof[1].rof1[0].vs  = 2'h0;
  assign \one_hot_encode.bsg.rof[1].rof1[1].vs  = 2'h0;
  assign \one_hot_encode.bsg.rof[1].rof1[2].vs  = 2'h0;
  assign \one_hot_encode.bsg.rof[1].rof1[3].vs  = sel_i[1:0];
  assign \one_hot_encode.bsg.rof[1].rof1[4].vs  = sel_i[3:2];
  assign \one_hot_encode.bsg.rof[1].rof1[5].vs  = sel_i[5:4];
  assign \one_hot_encode.bsg.rof[1].rof1[6].vs  = sel_i[7:6];
  assign \one_hot_encode.bsg.rof[1].rof1[7].vs  = sel_i[9:8];
  assign \one_hot_encode.bsg.rof[2].rof1[0].vs  = 2'h0;
  assign \one_hot_encode.bsg.rof[2].rof1[1].vs  = { \one_hot_encode.bsg.addr[4] [3], 1'h0 };
  assign \one_hot_encode.bsg.rof[2].rof1[2].vs  = { 1'hx, \one_hot_encode.bsg.addr[2] [9] };
  assign \one_hot_encode.bsg.rof[2].rof1[3].vs  = { 1'hx, \one_hot_encode.bsg.addr[2] [13] };
  assign \one_hot_encode.bsg.rof[3].rof1[0].vs  = { \one_hot_encode.bsg.addr[4] [3], 1'h0 };
  assign \one_hot_encode.bsg.rof[3].rof1[1].vs  = { 1'hx, \one_hot_encode.bsg.addr[3] [10] };
  assign \one_hot_encode.bsg.rof[4].rof1[0].vs  = { 1'hx, \one_hot_encode.bsg.addr[4] [3] };
  assign \one_hot_encode.bsg.v[0]  = { sel_i, 6'h00 };
  assign \one_hot_encode.bsg.v[1]  = { 3'hx, \one_hot_encode.bsg.addr[2] [13], 3'hx, \one_hot_encode.bsg.addr[2] [9], 1'hx, \one_hot_encode.bsg.addr[4] [3], 6'bx0x0x0 };
  assign \one_hot_encode.bsg.v[2]  = { 7'hxx, \one_hot_encode.bsg.addr[3] [10], 3'hx, \one_hot_encode.bsg.addr[4] [3], 4'bxxx0 };
  assign \one_hot_encode.bsg.v[3]  = { 15'hxxxx, \one_hot_encode.bsg.addr[4] [3] };
  assign \one_hot_encode.enc_o  = { \one_hot_encode.bsg.addr[4] [3], \one_hot_encode.bsg.addr[3] [10:9], \one_hot_encode.bsg.addr[4] [0] };
  assign \one_hot_encode.vec_i  = sel_i;
  assign sel_w = { \one_hot_encode.bsg.addr[4] [3], \one_hot_encode.bsg.addr[3] [10:9], \one_hot_encode.bsg.addr[4] [0] };
endmodule
