/* Generated by Yosys 0.45 (git sha1 9ed031ddd, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* \library  = "work" *)
(* hdlname = "one_hot_mux" *)
(* src = "priority_pre.sv:1.8-1.19" *)
module one_hot_mux(out_o, vec_i, sel_i);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[0] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[1] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[2] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[3] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[4] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[5] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[6] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[7] ;
  (* hdlname = "one_hot_encode bsg addr[0]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  wire [7:0] \one_hot_encode.bsg.addr[0] ;
  (* hdlname = "one_hot_encode bsg addr[1]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  wire [7:0] \one_hot_encode.bsg.addr[1] ;
  (* hdlname = "one_hot_encode bsg addr[2]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  (* unused_bits = "0 1 4 5" *)
  wire [7:0] \one_hot_encode.bsg.addr[2] ;
  (* hdlname = "one_hot_encode bsg addr[3]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  (* unused_bits = "0 1 2" *)
  wire [7:0] \one_hot_encode.bsg.addr[3] ;
  (* hdlname = "one_hot_encode bsg addr_o" *)
  (* src = "bsg_encode_one_hot.sv:15.32-15.38" *)
  (* unused_bits = "0 1 2" *)
  wire [2:0] \one_hot_encode.bsg.addr_o ;
  (* hdlname = "one_hot_encode bsg i" *)
  (* src = "bsg_encode_one_hot.sv:14.22-14.23" *)
  (* unused_bits = "0" *)
  wire [7:0] \one_hot_encode.bsg.i ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[0].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "0" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[0].vs ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[1].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[1].vs ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[2].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[2].vs ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[3].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[3].vs ;
  (* hdlname = "one_hot_encode bsg rof[2].rof1[0].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "1" *)
  wire [1:0] \one_hot_encode.bsg.rof[2].rof1[0].vs ;
  (* hdlname = "one_hot_encode bsg rof[2].rof1[1].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "1" *)
  wire [1:0] \one_hot_encode.bsg.rof[2].rof1[1].vs ;
  (* hdlname = "one_hot_encode bsg rof[3].rof1[0].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "1" *)
  wire [1:0] \one_hot_encode.bsg.rof[3].rof1[0].vs ;
  (* hdlname = "one_hot_encode bsg v[0]" *)
  (* src = "bsg_encode_one_hot.sv:27.44-27.45" *)
  (* unused_bits = "0" *)
  wire [7:0] \one_hot_encode.bsg.v[0] ;
  (* hdlname = "one_hot_encode bsg v[1]" *)
  (* src = "bsg_encode_one_hot.sv:27.44-27.45" *)
  (* unused_bits = "2 6" *)
  wire [7:0] \one_hot_encode.bsg.v[1] ;
  (* hdlname = "one_hot_encode bsg v[2]" *)
  (* src = "bsg_encode_one_hot.sv:27.44-27.45" *)
  (* unused_bits = "4" *)
  wire [7:0] \one_hot_encode.bsg.v[2] ;
  (* hdlname = "one_hot_encode enc_o" *)
  (* src = "priority_pre.sv:26.37-26.42" *)
  (* unused_bits = "0 1 2" *)
  wire [2:0] \one_hot_encode.enc_o ;
  (* hdlname = "one_hot_encode vec_i" *)
  (* src = "priority_pre.sv:25.28-25.33" *)
  (* unused_bits = "0" *)
  wire [7:0] \one_hot_encode.vec_i ;
  (* src = "priority_pre.sv:5.12-5.17" *)
  output out_o;
  wire out_o;
  (* src = "priority_pre.sv:3.27-3.32" *)
  input [7:0] sel_i;
  wire [7:0] sel_i;
  (* src = "priority_pre.sv:7.35-7.40" *)
  (* unused_bits = "0 1 2" *)
  wire [2:0] sel_w;
  (* src = "priority_pre.sv:4.27-4.32" *)
  input [7:0] vec_i;
  wire [7:0] vec_i;
  assign _00_ = ~(sel_i[1] | sel_i[3]);
  assign _01_ = sel_i[7] | sel_i[5];
  assign _02_ = _00_ & ~(_01_);
  assign _03_ = _02_ ? vec_i[0] : vec_i[1];
  assign _04_ = sel_i[3] | sel_i[2];
  assign _05_ = ~(sel_i[7] | sel_i[6]);
  assign _06_ = _05_ & ~(_04_);
  assign _07_ = _02_ ? vec_i[2] : vec_i[3];
  assign _08_ = _06_ ? _03_ : _07_;
  assign _09_ = sel_i[5] | sel_i[4];
  assign _10_ = _05_ & ~(_09_);
  assign _11_ = _02_ ? vec_i[4] : vec_i[5];
  assign _12_ = _02_ ? vec_i[6] : vec_i[7];
  assign _13_ = _06_ ? _11_ : _12_;
  assign out_o = _10_ ? _08_ : _13_;
  assign \elems[0]  = vec_i[0];
  assign \elems[1]  = vec_i[1];
  assign \elems[2]  = vec_i[2];
  assign \elems[3]  = vec_i[3];
  assign \elems[4]  = vec_i[4];
  assign \elems[5]  = vec_i[5];
  assign \elems[6]  = vec_i[6];
  assign \elems[7]  = vec_i[7];
  assign \one_hot_encode.bsg.addr[0]  = 8'hxx;
  assign \one_hot_encode.bsg.addr[1]  = { 1'hx, sel_i[7], 1'hx, sel_i[5], 1'hx, sel_i[3], 1'hx, sel_i[1] };
  assign { \one_hot_encode.bsg.addr[2] [7:6], \one_hot_encode.bsg.addr[2] [3:2] } = 4'hx;
  assign \one_hot_encode.bsg.addr[3] [7:3] = 5'hxx;
  assign \one_hot_encode.bsg.addr_o  = \one_hot_encode.bsg.addr[3] [2:0];
  assign \one_hot_encode.bsg.i  = sel_i;
  assign \one_hot_encode.bsg.rof[1].rof1[0].vs  = sel_i[1:0];
  assign \one_hot_encode.bsg.rof[1].rof1[1].vs  = sel_i[3:2];
  assign \one_hot_encode.bsg.rof[1].rof1[2].vs  = sel_i[5:4];
  assign \one_hot_encode.bsg.rof[1].rof1[3].vs  = sel_i[7:6];
  assign \one_hot_encode.bsg.rof[2].rof1[0].vs  = { \one_hot_encode.bsg.addr[2] [1], 1'hx };
  assign \one_hot_encode.bsg.rof[2].rof1[1].vs  = { \one_hot_encode.bsg.addr[2] [5], 1'hx };
  assign \one_hot_encode.bsg.rof[3].rof1[0].vs  = { \one_hot_encode.bsg.addr[3] [2], 1'hx };
  assign \one_hot_encode.bsg.v[0]  = sel_i;
  assign \one_hot_encode.bsg.v[1]  = { 1'hx, \one_hot_encode.bsg.addr[2] [5], 3'hx, \one_hot_encode.bsg.addr[2] [1], 2'hx };
  assign \one_hot_encode.bsg.v[2]  = { 3'hx, \one_hot_encode.bsg.addr[3] [2], 4'hx };
  assign \one_hot_encode.enc_o  = \one_hot_encode.bsg.addr[3] [2:0];
  assign \one_hot_encode.vec_i  = sel_i;
  assign sel_w = \one_hot_encode.bsg.addr[3] [2:0];
endmodule
