/* Generated by Yosys 0.45 (git sha1 9ed031ddd, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* hdlname = "dff" *)
(* \library  = "work" *)
(* top =  1  *)
(* src = "dff.sv:4.8-4.11" *)
module dff(reset_i, d_i, en_i, q_o, clk_i);
  (* src = "dff.sv:6.16-6.21" *)
  input clk_i;
  wire clk_i;
  (* src = "dff.sv:8.16-8.19" *)
  input d_i;
  wire d_i;
  (* src = "dff.sv:9.16-9.20" *)
  input en_i;
  wire en_i;
  (* src = "dff.sv:10.17-10.20" *)
  output q_o;
  wire q_o;
  (* src = "dff.sv:13.16-13.19" *)
  reg q_r;
  (* src = "dff.sv:7.16-7.23" *)
  input reset_i;
  wire reset_i;
  (* src = "dff.sv:26.10-28.31" *)
  always @(posedge clk_i)
    if (reset_i) q_r <= 1'h0;
    else if (en_i) q_r <= d_i;
  assign q_o = q_r;
endmodule
