/* Generated by Yosys 0.45 (git sha1 9ed031ddd, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* \library  = "work" *)
(* hdlname = "one_hot_mux" *)
(* src = "priority_pre.sv:1.8-1.19" *)
module one_hot_mux(out_o, vec_i, sel_i);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[0] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[1] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[2] ;
  (* src = "priority_pre.sv:14.16-14.21" *)
  wire \elems[3] ;
  (* hdlname = "one_hot_encode bsg addr[0]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  wire [3:0] \one_hot_encode.bsg.addr[0] ;
  (* hdlname = "one_hot_encode bsg addr[1]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  wire [3:0] \one_hot_encode.bsg.addr[1] ;
  (* hdlname = "one_hot_encode bsg addr[2]" *)
  (* src = "bsg_encode_one_hot.sv:26.44-26.48" *)
  (* unused_bits = "0 1" *)
  wire [3:0] \one_hot_encode.bsg.addr[2] ;
  (* hdlname = "one_hot_encode bsg addr_o" *)
  (* src = "bsg_encode_one_hot.sv:15.32-15.38" *)
  (* unused_bits = "0 1" *)
  wire [1:0] \one_hot_encode.bsg.addr_o ;
  (* hdlname = "one_hot_encode bsg i" *)
  (* src = "bsg_encode_one_hot.sv:14.22-14.23" *)
  (* unused_bits = "0" *)
  wire [3:0] \one_hot_encode.bsg.i ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[0].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "0" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[0].vs ;
  (* hdlname = "one_hot_encode bsg rof[1].rof1[1].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  wire [1:0] \one_hot_encode.bsg.rof[1].rof1[1].vs ;
  (* hdlname = "one_hot_encode bsg rof[2].rof1[0].vs" *)
  (* src = "bsg_encode_one_hot.sv:41.22-41.24" *)
  (* unused_bits = "1" *)
  wire [1:0] \one_hot_encode.bsg.rof[2].rof1[0].vs ;
  (* hdlname = "one_hot_encode bsg v[0]" *)
  (* src = "bsg_encode_one_hot.sv:27.44-27.45" *)
  (* unused_bits = "0" *)
  wire [3:0] \one_hot_encode.bsg.v[0] ;
  (* hdlname = "one_hot_encode bsg v[1]" *)
  (* src = "bsg_encode_one_hot.sv:27.44-27.45" *)
  (* unused_bits = "2" *)
  wire [3:0] \one_hot_encode.bsg.v[1] ;
  (* hdlname = "one_hot_encode enc_o" *)
  (* src = "priority_pre.sv:26.37-26.42" *)
  (* unused_bits = "0 1" *)
  wire [1:0] \one_hot_encode.enc_o ;
  (* hdlname = "one_hot_encode vec_i" *)
  (* src = "priority_pre.sv:25.28-25.33" *)
  (* unused_bits = "0" *)
  wire [3:0] \one_hot_encode.vec_i ;
  (* src = "priority_pre.sv:5.12-5.17" *)
  output out_o;
  wire out_o;
  (* src = "priority_pre.sv:3.27-3.32" *)
  input [3:0] sel_i;
  wire [3:0] sel_i;
  (* src = "priority_pre.sv:7.35-7.40" *)
  (* unused_bits = "0 1" *)
  wire [1:0] sel_w;
  (* src = "priority_pre.sv:4.27-4.32" *)
  input [3:0] vec_i;
  wire [3:0] vec_i;
  assign _2_ = ~(sel_i[1] | sel_i[3]);
  assign _3_ = vec_i[0] & ~(_2_);
  assign _0_ = ~(sel_i[3] | sel_i[2]);
  assign _1_ = _2_ ? vec_i[1] : vec_i[2];
  assign out_o = _0_ ? _3_ : _1_;
  assign \elems[0]  = 1'hx;
  assign \elems[1]  = vec_i[0];
  assign \elems[2]  = vec_i[1];
  assign \elems[3]  = vec_i[2];
  assign \one_hot_encode.bsg.addr[0]  = 4'hx;
  assign \one_hot_encode.bsg.addr[1]  = { 1'hx, sel_i[3], 1'hx, sel_i[1] };
  assign \one_hot_encode.bsg.addr[2] [3:2] = 2'hx;
  assign \one_hot_encode.bsg.addr_o  = \one_hot_encode.bsg.addr[2] [1:0];
  assign \one_hot_encode.bsg.i  = sel_i;
  assign \one_hot_encode.bsg.rof[1].rof1[0].vs  = sel_i[1:0];
  assign \one_hot_encode.bsg.rof[1].rof1[1].vs  = sel_i[3:2];
  assign \one_hot_encode.bsg.rof[2].rof1[0].vs  = { \one_hot_encode.bsg.addr[2] [1], 1'hx };
  assign \one_hot_encode.bsg.v[0]  = sel_i;
  assign \one_hot_encode.bsg.v[1]  = { 1'hx, \one_hot_encode.bsg.addr[2] [1], 2'hx };
  assign \one_hot_encode.enc_o  = \one_hot_encode.bsg.addr[2] [1:0];
  assign \one_hot_encode.vec_i  = sel_i;
  assign sel_w = \one_hot_encode.bsg.addr[2] [1:0];
endmodule
